### ISSUE TITLE
missing Operand

### ISSUE THREAD

**Issue by docgonzo2015** [tclscripts/YoutubeTitle#1]
I'm getting a failure. 

`Tcl error [check:youtube]: missing operand at _@_
in expression "( - _@_)"
missing operand at _@_
in expression "( - _@_)"
(parsing expression "( - )")
invoked from within
"expr ($dislike - $like)"
(procedure "youtube:like_bar" line 9)
invoked from within
"youtube:like_bar $likes $dontlike $chan"
(procedure "youtube:get:title" line 29)
invoked from within
"youtube:get:title $youtube_link $nick $chan 0"
(procedure "check:youtube" line 13)
invoked from within
"check:youtube $_pubm1 $_pubm2 $_pubm3 $_pubm4 $_pubm5"`

**Comment by DanielVoipan** [comment]
Download it again from -> https://www.tclscripts.net/files/file/3-youtubetitletcl/

**Comment by DanielVoipan** [comment]
Solved, new version.
